services:
  asm-app:
    build: .
    container_name: apple_school_manager_v2
    ports:
      - "8080:6000"
    volumes:
      # Mappa undermappen med koden till /app i containern
      - ./apple_school_manager_with_gui_and_assign:/app
      # Se till att customers-mappen fortfarande mappas korrekt
      - ./customers:/app/admin_api/customers
      # Persistent volym för GSX API-nyckel och annan data
      - gsxdata:/data
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=true # Aktiverar live-reload för Flask
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=6000
      - PYTHONPATH=/app
      - DEFAULT_ROUTE=frontend
    restart: unless-stopped

  #react-frontend:
    # build:
    #   context: ./apple_school_manager_with_gui_and_assign/react-frontend
    #   dockerfile: Dockerfile
    # container_name: react_frontend
    # ports:
    #   - "3000:3000"
    # working_dir: /app
    # volumes:
    #   - ./apple_school_manager_with_gui_and_assign/react-frontend:/app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # restart: unless-stopped

volumes:
  gsxdata:
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # restart: unless-stopped

# volumes:
#   gsxdata:

