services:
  asm-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apple_school_manager_dev
    ports:
      - "8080:6000"
    volumes:
      - ./customers:/app/admin_api/customers
      - ./apple_school_manager_with_gui_and_assign:/app
      - /var/run/docker.sock:/var/run/docker.sock  # För auto-rebuild
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=6000
      - PYTHONPATH=/app
    restart: unless-stopped
    
  git-sync:
    image: alpine/git
    container_name: git-sync
    volumes:
      - .:/git/repo
    working_dir: /git/repo
    command: |
      sh -c "
        while true; do
          git fetch origin
          LOCAL=\$$(git rev-parse HEAD)
          REMOTE=\$$(git rev-parse origin/main)
          if [ \$$LOCAL != \$$REMOTE ]; then
            echo 'Changes detected, pulling...'
            git pull origin main
            docker-compose restart asm-app
          fi
          sleep 60
        done
      "
    restart: unless-stopped
