name: Docker Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t apple-school-manager:${{ github.sha }} .
        
    - name: Test Docker image
      run: |
        # Start the container
        docker run -d --name test-container -p 6000:6000 apple-school-manager:${{ github.sha }}
        
        # Wait for container to start
        sleep 30
        
        # Test health endpoint
        curl -f http://localhost:6000/health || exit 1
        
        # Stop container
        docker stop test-container
        docker rm test-container
        
    - name: Clean up
      if: always()
      run: |
        docker stop test-container || true
        docker rm test-container || true
        docker rmi apple-school-manager:${{ github.sha }} || true
        echo "Deploying to production server..."
        # SSH till din server och kör docker-compose
